### ISSUE TITLE
Add FindByPlayerName to PlayerDAO

### ISSUE THREAD

**Issue by antoniopetrole** [T1NKY-W1NKY/AMF#3]
## Start with **WHY**?
Why do we need to do work? (Who is requesting this work?)
Currently our application will make a call to the Apex API every time someone searches for a player. This over time will lead to us overusing the number of requests that we have to the API and will stall our app. This story is to implement a FindByPlayerName(playerName) method to the playerDAO. This will allow us to search for existing players when someone searches for a player so we can avoid hitting the Apex Api if we can. This will lead to follow up stories around how we update out of date player information such as current level. 

## What is the issue?  What needs to be resolved?

* **AS A** App maintainer
* **I WANT** see if a searched player already exists
* **SO THAT** we can avoid calling the Apex API if we can
* 
Acceptance Criteria
* **GIVEN** I already have the player "traepsy" in the database
* **WHEN** I search for traepsy in the player search bar
* **THEN** it returns the database results as opposed to calling the API

## Any other notes / resources to share?

**Comment by antoniopetrole** [comment]
Commits can be found here https://github.com/T1NKY-W1NKY/AMF/commit/e04dd8d33e78645544a1821a9629d5757275dc8e

**Comment by lightableMatch** [comment]
Did not update issue with commits when working on it.
These are the noteworthy commits:
- Method added and finished here: e9b3f604a607728b17bdcb4912482b065dd315e5
