### ISSUE TITLE
Persist AMF Object To Database

### ISSUE THREAD

**Issue by antoniopetrole** [T1NKY-W1NKY/AMF#5]
## Start with **WHY**?
Why do we need to do work? (Who is requesting this work?)
Currently we call the Apex API every single time web site is loaded which will very quickly lock out our API access. We need to persist the current map rotation to the database so we pull the data locally on subsequent page loads. This story is to persist the AMF object to the database

## What is the issue?  What needs to be resolved?

* **AS A** App developer
* **I WANT** to persist the AMF object
* **SO THAT** I don't lose API access

Acceptance Criteria
* **GIVEN** I have loaded the page once before
* **WHEN** I reload the page
* **THEN** I pull the map rotation data from the local database

## Any other notes / resources to share?

**Comment by antoniopetrole** [comment]
Remember to include the @OneToOne(cascade = {CascadeType.ALL}) annotation in your object mappings

**Comment by lightableMatch** [comment]
Did not update issue with commits when working on it.
These are the noteworthy commits:
- First implementation: 305838a49850872972cf63aef0e66de519d139a4
- Finished: 05510edd4793c928482ff3a0b310c50af8193731
