### ISSUE TITLE
Add Functionality To Update Map Rotations After Persistence

### ISSUE THREAD

**Issue by antoniopetrole** [T1NKY-W1NKY/AMF#6]
## Start with **WHY**?
Why do we need to do work? (Who is requesting this work?)
Once the story below has been implemented, any subsequent page loads to the home page will permanently give the user out of date information
https://github.com/T1NKY-W1NKY/AMF/issues/5

To mitigate this behavior, we need to rehydrate the map rotations via the apex API once the maps change. I would look into the following possible solutions
1. (HARDER BUT BETTER) Look into dynamically configuring a spring boot @Scheduled method that will rehydrate the map rotation data based on the end time UNIX EPOCH timestamp. 
2. (EASIER BUT NOT ROBUST) Look into statically configuring a spring boot @Scheduled method that will rehydrate the map rotation based on some fixed interval

## What is the issue?  What needs to be resolved?

* **AS A** 
* **I WANT** 
* **SO THAT** 

Acceptance Criteria
* **GIVEN** 
* **WHEN** 
* **THEN** 

## Any other notes / resources to share?

**Comment by lightableMatch** [comment]
Did not update issue with commits when working on it.
These are the noteworthy commits:
- Closed issue on this working timer: f7c5a14a4938178ba85f1b6f19e37befdfeb0f72
- Timer was polished up a bit: c89f9fac3b1d9ecc3a79398c2ab7457717c4ff24
