### ISSUE TITLE
PLACEHOLDER REMOVE SECRETS FROM CODE

### ISSUE THREAD

**Issue by antoniopetrole** [T1NKY-W1NKY/AMF#7]
Look into environment variables

**Comment by lightableMatch** [comment]
Done: e75297c37d4b8494df6b8718e569b3703cbbb13a

-Not in master yet...
-Created a hidden properties file that held the values

**Comment by lightableMatch** [comment]
Merged to Master

**Comment by lightableMatch** [comment]
Secrets have been removed from code but **a different method is being used since issue was closed.**
- Now environment variables from the system are being used
- Reference to environment variables are in _application.properties_
